### ISSUE TITLE
写这么多，其实两句代码就可以实现，并且不要求aero

### ISSUE THREAD

**Issue by goodhelp** [nlysh007/aardio-wallpaper#1]
你写那么多，还写了个扩展库，不符合aardio风格，其实两句代码就实现了任意窗口嵌入桌面
var pwnd=win.find("Progman","Program Manager");
win.setParent(mainForm.hwnd,pwnd);//嵌入桌面

并且你的扩展库，直接中止程序还会留下空白，不刷新桌面!

**Comment by nlysh007** [comment]
首先这个库不是将窗口嵌入桌面，而是放入桌面图标和壁纸之间，
其次你关闭子窗口应该在form.onClose事件里主动去移除/恢复wallpaper窗口，
且wallpaper.removeWindow 里面已经处理了可能的窗口残留
即便异常关闭也可以wallpaper.clearWindow(true)去清理窗口，

**Comment by goodhelp** [comment]
你没测试过？win7开启了aero，运行fliplo_desktop这个（不知道是不是你写的https://github.com/leejoker/fliplo_desktop），中止程序，桌面一片白，恢复不了了!不用这代码，写出来中止程序也是桌面背景一片空白!
哦，对了，steam上的wallpaperengine也是采用的我说的这两行代码!

**Comment by nlysh007** [comment]
1. 我测试过（普通窗口程序、视频播放程序），可能没有覆盖到全部系统和程序
2. fliplo_desktop不是我是写的
